<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.idunou.myplace</groupId>
    <artifactId>myplace-parent</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
        <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
        <quarkus.platform.version>3.38.3</quarkus.platform.version> <!-- reference https://mvnrepository.com/artifact/io.quarkus.platform/quarkus-bom for latest version -->
        <compiler.plugin.version>3.15.0</compiler.plugin.version> <!-- reference https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-compiler-plugin for latest version -->
        
        <surefire.plugin.version>3.5.6</surefire.plugin.version> <!-- reference https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-surefire-plugin for latest version -->
        <jSerialComm.version>[2.11.4,3.0.0)</jSerialComm.version> <!-- reference https://mvnrepository.com/artifact/com.fazecast/jSerialComm for latest version -->

        <node.version>v26.7.0</node.version> <!-- reference https://nodejs.org/en/download/releases/ for latest version -->
        <npm.version>12.0.2</npm.version> <!-- reference https://www.npmjs.com/package/npm for latest version -->
        
        <maven.resources.plugin.version>3.5.0</maven.resources.plugin.version> <!-- reference https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-resources-plugin for latest version -->
        <maven.clean.plugin.version>3.5.0</maven.clean.plugin.version> <!-- reference https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-clean-plugin for latest version -->
        <frontend.maven.plugin.version>2.0.1</frontend.maven.plugin.version> <!-- reference https://mvnrepository.com/artifact/com.github.eirslett/frontend-maven-plugin for latest version -->

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>17</maven.compiler.release>
        <maven.compiler.parameters>true</maven.compiler.parameters>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>${quarkus.platform.artifact-id}</artifactId>
                <version>${quarkus.platform.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>



    <profiles>
		<profile>
			<id>parent</id>
			<activation />
		</profile>
		<profile>
			<id>build</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<modules>
                <module>myplace</module>
                <module>myplace-frontend</module>
            </modules>
		</profile>
	</profiles>
    <build>
        <plugins>
            <plugin>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus.platform.version}</version>
                <extensions>true</extensions>
            </plugin>
        </plugins>
    </build>
</project>